### ISSUE TITLE
Improve Elasticsearch logging

### ISSUE THREAD

**Issue by osdemah** [vmfarms/terraform-aws-elasticsearch#11]
# DoD
- [ ] Adjust terraform module to ship all the logs to Cloudwatch logs
- [ ] Ship logs to Elasticsearch

# Notes

We have no logging enabled for the created ES cluster. We need to add some options to let people enable logging for their clusters. it includes:

- slow searches
- slow indexes
- errors

**Comment by daniel-araya5813** [comment]
https://github.com/vmfarms/terraform-aws-elasticsearch/blob/master/main.tf
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createdomain-configure-slow-logs.html
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createdomain-configure-slow-logs.html#es-createdomain-configure-slow-logs-cli

**Comment by daniel-araya5813** [comment]
Enabling advanced elasticSearch Logging requires enabling many other security settings.
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/fgac.html#fgac-access-policies

I'm currently adjusting the files based on the security dependency errors that pop-up. Previous errors:
```
Error: Error creating ElasticSearch domain: ValidationException: audit log publishing cannot be enabled as you do not have advanced security options configured.
Error: Error creating ElasticSearch domain: ValidationException: You must enable node-to-node encryption to use advanced security options.
Error: Error creating ElasticSearch domain: ValidationException: You must enable EnforceHTTPS in the domain endpoint options to use advanced security.
Error: Error creating ElasticSearch domain: ValidationException: 1 validation error detected: Value '' at 'domainEndpointOptions.tLSSecurityPolicy' failed to satisfy constraint: Member must satisfy enum value set: [Policy-Min-TLS-1-0-2019-07, Policy-Min-TLS-1-2-2019-07]
```

**Comment by daniel-araya5813** [comment]
I'll be enabling Amazon Cognito authentication for Kibana, this method allows authentication through IAM users and is preferred for clients with multiple ES domains, such as Careguide.

The alternative would be creating multiple "Basic Authentication" Credentials for each ES domain.

**Comment by daniel-araya5813** [comment]
With the current configuration the latest security request is

"Error: Error creating ElasticSearch domain: ValidationException: You must provide a master username and password when the internal user database is enabled."

I considered using the Cognito service as an alternative, but there's a considerable amount of configuration to be considered. I will go about providing the master username/database

**Comment by daniel-araya5813** [comment]
PR https://github.com/vmfarms/terraform-aws-elasticsearch/pull/12/files

**Comment by ec209** [comment]
@daniel-araya5813 - left my review

**Comment by ec209** [comment]
the ES logs are not appearing on CW, someone need to tackle this.

**Comment by osdemah** [comment]
We did not have to enable audit logging. Because our customers are using elasticseacrh without authentication and their endpoint is in a private network. So I just enabled slow saech, slow index and application logs. Here is the PR: https://github.com/vmfarms/terraform-aws-elasticsearch/pull/13

**Comment by dpolitiuk** [comment]
Approved PR.
